version: 2.1

jobs:
  build_all:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: test
          command: echo "here in build_all will be the rest of the pipeline except the ones for QA that needs to be on dev maaster and stage branches"

  build:
    docker:
      - image: circleci/node:14
        environment:
          CI: true
          REACT_APP_SERVER_URL: http://react-app:3000


    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      #Clone the Playwright tests repository to a different directory within the workspace
      - run:
          name: Clone Playwright tests repository
          command: git clone https://github.com/MohamedEssam4444/docker-compose-QA-testing.git

      # Use Docker-Compose to run both services together
      - run:
          name: Run React app and Playwright tests
          command: |
            echo ${GITHUB_TOKEN}
            cd docker-compose-QA-testing
            docker-compose build --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} react-app
            docker-compose up -d
            docker-compose run playwright-tests npx -y playwright test

      - store_test_results:
          path: ./outcome/test-results/results.xml

      - store_artifacts:
          path: ./outcome/html

      # Clean up containers after the tests complete
      - run:
          name: Cleanup
          command: |
            docker-compose down

# Define workflows

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_all

      - build:
          filters:
            branches:
              only:
                - dev
                - stage
                - master
                - main