version: 2.1
jobs:
  npm_install:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-123
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-123
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-123
      - setup_remote_docker:
          docker_layer_caching: false

      # - run:
      #     name: docker commands
      #     command: |
      #       # container_name=$(cat /etc/hostname)
      #       # network_name=$(docker inspect $container_name --format '{{ range $name, $conf := .NetworkSettings.Networks }}{{ $name }}{{ end }}')
      #       # network_name_without_suffix=${network_name%bridge}
      #       # docker network inspect $network_name_without_suffix
      #       container_ip=$(docker network inspect bridge | jq -r '.[0].Containers | to_entries[0].value.IPv4Address' | cut -d '/' -f 1)
      #       echo $container_ip
      #       docker ps 
      #       docker images
      #       docker network ls


      # Start the React app in the background
      - run:
          name: Start App Container
          command: npm start
          background: true

      - run:
          name: Clone Playwright tests repository
          command: |
            git clone git@github.com:sftqa/m_pw.git /home/circleci/project/m_pw
            cd /home/circleci/project/m_pw
            git checkout optimize_ci_pw
            mv docker-merchant-dashboard/Dockerfile .


      - run:
          name: Run Playwright Tests
          command: |
            cd /home/circleci/project/m_pw  
            container_name=$(docker ps --format "{{.Names}}" --filter "ancestor=circleci/node:14")

            # Get the Container ID from the Container Name
            container_id=$(docker ps -q -f name=$container_name)

            # Get the Container IP Address and Network Name using docker inspect
            container_info=$(docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}} {{.NetworkID}}{{end}}' $container_id)
            container_ip=$(echo $container_info | awk '{print $1}')
            network_id=$(echo $container_info | awk '{print $2}')

            # Get the Network Name using docker network inspect
            network_name=$(docker network inspect -f '{{.Name}}' $network_id)

            echo "Container Name: $container_name"
            echo "Container IP: $container_ip"
            echo "Network Name: $network_name"



            docker ps 
            docker images
            docker network ls
            # docker build -t playwright-tests .
            # docker run --rm --network $network_name --name qa -e REACT_APP_SERVER_URL=$container_ip:3000  playwright-tests npx playwright test

      - store_test_results:
          path: /home/circleci/project/m_pw/test-results/results.xml

      - store_artifacts:
          path: ./test-results 

workflows:
  version: 2
  install_and_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
                - stage
                - master
                - main
                - optimize_ci
