version: 2.1
jobs:
  npm_install:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-123
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-123
          paths:
            - ./node_modules

  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.36.1
      - image: circleci/node:14
    steps:
      - checkout #merchant rep
      - restore_cache:
          key: dependency-cache-123
      - setup_remote_docker:
          docker_layer_caching: false

      - run:
          name: Clone Playwright repo, get ready
          command: |
            git clone git@github.com:sftqa/m_pw.git /home/circleci/project/m_pw
            cd /home/circleci/project/m_pw
            git checkout optimize_ci_pw
            npm install

      - run:
          name: docker commands
          command: |
                docker run -v /home/circleci/project/:/app --name react-app -p 9000:9000 -d circleci/node:14

      # Start the React app in the background
      - run:
          name: Start App Container
          command: npm start
          background: true

      - run:
          name: Start server in background
          command: |
            docker exec -d react-app npm start


      - run:
          name: Run Playwright Tests
          command: | 
            cd /home/circleci/project/m_pw 
            npx playwright-tests npx playwright test

      - store_test_results:
          path: /home/circleci/project/m_pw/outcome/test-results/results.xml

      - store_artifacts:
          path: /home/circleci/project/m_pw/outcome/html 

workflows:
  version: 2
  install_and_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - dev
                - stage
                - master
                - main
                - optimize_ci
