version: 2.1
jobs:
  npm_install:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-123
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-123
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-123
      - setup_remote_docker:
          docker_layer_caching: true

      # Start the React app in the background
      - run:
          name: Start App Container
          command: npm run start
          background: true

      - run:
          name: Clone Playwright tests repository
          command: git clone git@github.com:sftqa/m_pw.git /

      - run:
          name: Run Playwright Tests
          command: |
            # Build the Docker image using the Dockerfile in m_pw repo
            docker build -t playwright-tests /docker-merchant-dashboard/

            # Run Playwright tests using the built Docker image
            docker run --rm --network="host" playwright-tests npx playwright test

      - store_test_results:
          path: ./test-results/results.xml

      - store_artifacts:
          path: ./test-results 

workflows:
  version: 2
  install_and_test:
    jobs:
      - npm_install
      - test:
          requires:
            - npm_install
          filters:
            branches:
              only:
                - dev
                - stage
                - master
                - main
                - optimize_ci
